const fs = require('node:fs');
const { execFileSync } = require('node:child_process');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const git = args => execFileSync('git', ['-c', `safe.directory=${root}`, ...args], { cwd: root, maxBuffer: 64 * 1024 * 1024 });
const findings = [];
// Default includes fetched remote history. Local-only mode helps validate a
// replacement before an explicitly authorized remote history update.
const revisions = process.argv.includes('--local') ? ['--branches', '--tags', 'HEAD'] : ['--all'];
function inspect(label, content) {
  const text = content.toString('utf8');
  const emails = text.match(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/gi) || [];
  if (emails.some(email => !/@(?:example\.(?:com|org|net|invalid)|users\.noreply\.github\.com)$/i.test(email))) findings.push(`${label}: non-placeholder email`);
  if (/[A-Z]:[\\/]+Users[\\/]+[\w.-]+|\/(?:Users|home)\/[\w.-]+/i.test(text)) findings.push(`${label}: personal filesystem path`);
  if (/(?:AIza[\w-]{35}|gh[pousr]_[A-Za-z0-9]{30,}|-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----)/.test(text)) findings.push(`${label}: possible credential`);
  if (/^Co-authored-by:.*(?:bot|assistant)|^generated by (?:ChatGPT|Codex|Claude)/im.test(text)) findings.push(`${label}: generated attribution`);
}
const working = git(['ls-files', '--cached', '--others', '--exclude-standard', '-z']).toString().split('\0').filter(Boolean);
for (const file of new Set(working)) {
  const full = path.join(root, file);
  if (fs.existsSync(full) && fs.statSync(full).isFile() && !/\.(?:png|vsix|jpg)$/i.test(file)) inspect(`working/${file}`, fs.readFileSync(full));
}
inspect('commit metadata', git(['log', ...revisions, '--format=%an <%ae>%n%cn <%ce>%n%B']));
const objects = git(['rev-list', '--objects', ...revisions]).toString().trim().split('\n').map(line => {
  const split = line.indexOf(' '); return { id: split < 0 ? line : line.slice(0, split), name: split < 0 ? '' : line.slice(split + 1) };
});
const batch = execFileSync('git', ['-c', `safe.directory=${root}`, 'cat-file', '--batch'], {
  cwd: root, input: objects.map(o => o.id).join('\n') + '\n', maxBuffer: 64 * 1024 * 1024
});
let offset = 0, blobs = 0;
for (const object of objects) {
  const end = batch.indexOf(10, offset), header = batch.subarray(offset, end).toString().split(' ');
  const size = Number(header[2]), content = batch.subarray(end + 1, end + 1 + size);
  if (header[1] === 'blob' && !content.includes(0)) { inspect(`history/${object.name || object.id.slice(0, 8)}`, content); blobs++; }
  offset = end + 1 + size + 1;
}
if (findings.length) { console.error([...new Set(findings)].join('\n')); process.exitCode = 1; }
else console.log(`Privacy audit passed (${process.argv.includes('--local') ? 'local branches and tags only' : 'all reachable history'}): ${new Set(working).size} working files, ${blobs} historical text blobs, and commit metadata. Pattern-based scan; manual review still required.`);
